/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as BookAVisitRouteImport } from './routes/book-a-visit'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ParentPortalRouteImport } from './routes/parent-portal'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions/index'
import { Route as AdmissionsEntryGuideRouteImport } from './routes/admissions/entry-guide'
import { Route as AdmissionsFaqsRouteImport } from './routes/admissions/faqs'
import { Route as AdmissionsFeesRouteImport } from './routes/admissions/fees'
import { Route as AdmissionsHowToApplyRouteImport } from './routes/admissions/how-to-apply'
import { Route as AdmissionsRequirementsRouteImport } from './routes/admissions/requirements'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ContactEnquiryRouteImport } from './routes/contact/enquiry'
import { Route as ContactFindUsRouteImport } from './routes/contact/find-us'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as LearningAssessmentRouteImport } from './routes/learning/assessment'
import { Route as LearningCultureValuesRouteImport } from './routes/learning/culture-values'
import { Route as LearningCurriculumRouteImport } from './routes/learning/curriculum'
import { Route as LearningDigitalLearningRouteImport } from './routes/learning/digital-learning'
import { Route as LearningEarlyYearsRouteImport } from './routes/learning/early-years'
import { Route as LearningEnrichmentRouteImport } from './routes/learning/enrichment'
import { Route as LearningPrimaryRouteImport } from './routes/learning/primary'
import { Route as LearningSubjectsRouteImport } from './routes/learning/subjects'
import { Route as OurSchoolIndexRouteImport } from './routes/our-school/index'
import { Route as OurSchoolAboutRouteImport } from './routes/our-school/about'
import { Route as OurSchoolFacilitiesRouteImport } from './routes/our-school/facilities'
import { Route as OurSchoolPoliciesRouteImport } from './routes/our-school/policies'
import { Route as OurSchoolSafeguardingRouteImport } from './routes/our-school/safeguarding'
import { Route as OurSchoolStaffRouteImport } from './routes/our-school/staff'
import { Route as OurSchoolVisionValuesRouteImport } from './routes/our-school/vision-values'
import { Route as OurSchoolWelcomeRouteImport } from './routes/our-school/welcome'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as ParentsAttendanceRouteImport } from './routes/parents/attendance'
import { Route as ParentsHealthWellbeingRouteImport } from './routes/parents/health-wellbeing'
import { Route as ParentsHomeworkReadingRouteImport } from './routes/parents/homework-reading'
import { Route as ParentsMealsRouteImport } from './routes/parents/meals'
import { Route as ParentsSchoolDayRouteImport } from './routes/parents/school-day'
import { Route as ParentsTermDatesRouteImport } from './routes/parents/term-dates'
import { Route as ParentsUniformRouteImport } from './routes/parents/uniform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAVisitRoute = BookAVisitRouteImport.update({
  id: '/book-a-visit',
  path: '/book-a-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentPortalRoute = ParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsEntryGuideRoute = AdmissionsEntryGuideRouteImport.update({
  id: '/entry-guide',
  path: '/entry-guide',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AdmissionsFaqsRoute = AdmissionsFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AdmissionsFeesRoute = AdmissionsFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AdmissionsHowToApplyRoute = AdmissionsHowToApplyRouteImport.update({
  id: '/how-to-apply',
  path: '/how-to-apply',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AdmissionsRequirementsRoute = AdmissionsRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AdmissionsRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactEnquiryRoute = ContactEnquiryRouteImport.update({
  id: '/contact/enquiry',
  path: '/contact/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactFindUsRoute = ContactFindUsRouteImport.update({
  id: '/contact/find-us',
  path: '/contact/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningAssessmentRoute = LearningAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => LearningRoute,
} as any)
const LearningCultureValuesRoute = LearningCultureValuesRouteImport.update({
  id: '/culture-values',
  path: '/culture-values',
  getParentRoute: () => LearningRoute,
} as any)
const LearningCurriculumRoute = LearningCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => LearningRoute,
} as any)
const LearningDigitalLearningRoute = LearningDigitalLearningRouteImport.update({
  id: '/digital-learning',
  path: '/digital-learning',
  getParentRoute: () => LearningRoute,
} as any)
const LearningEarlyYearsRoute = LearningEarlyYearsRouteImport.update({
  id: '/early-years',
  path: '/early-years',
  getParentRoute: () => LearningRoute,
} as any)
const LearningEnrichmentRoute = LearningEnrichmentRouteImport.update({
  id: '/enrichment',
  path: '/enrichment',
  getParentRoute: () => LearningRoute,
} as any)
const LearningPrimaryRoute = LearningPrimaryRouteImport.update({
  id: '/primary',
  path: '/primary',
  getParentRoute: () => LearningRoute,
} as any)
const LearningSubjectsRoute = LearningSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => LearningRoute,
} as any)
const OurSchoolIndexRoute = OurSchoolIndexRouteImport.update({
  id: '/our-school/',
  path: '/our-school/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurSchoolAboutRoute = OurSchoolAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => OurSchoolRoute,
} as any)
const OurSchoolFacilitiesRoute = OurSchoolFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => OurSchoolRoute,
} as any)
const OurSchoolPoliciesRoute = OurSchoolPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => OurSchoolRoute,
} as any)
const OurSchoolSafeguardingRoute = OurSchoolSafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => OurSchoolRoute,
} as any)
const OurSchoolStaffRoute = OurSchoolStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OurSchoolRoute,
} as any)
const OurSchoolVisionValuesRoute = OurSchoolVisionValuesRouteImport.update({
  id: '/vision-values',
  path: '/vision-values',
  getParentRoute: () => OurSchoolRoute,
} as any)
const OurSchoolWelcomeRoute = OurSchoolWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OurSchoolRoute,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsAttendanceRoute = ParentsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsHealthWellbeingRoute = ParentsHealthWellbeingRouteImport.update({
  id: '/health-wellbeing',
  path: '/health-wellbeing',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsHomeworkReadingRoute = ParentsHomeworkReadingRouteImport.update({
  id: '/homework-reading',
  path: '/homework-reading',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsMealsRoute = ParentsMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsSchoolDayRoute = ParentsSchoolDayRouteImport.update({
  id: '/school-day',
  path: '/school-day',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsTermDatesRoute = ParentsTermDatesRouteImport.update({
  id: '/term-dates',
  path: '/term-dates',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsUniformRoute = ParentsUniformRouteImport.update({
  id: '/uniform',
  path: '/uniform',
  getParentRoute: () => ParentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/book-a-visit': typeof BookAVisitRoute
  '/calendar': typeof CalendarRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-portal': typeof ParentPortalRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/admissions/entry-guide': typeof AdmissionsEntryGuideRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/fees': typeof AdmissionsFeesRoute
  '/admissions/how-to-apply': typeof AdmissionsHowToApplyRoute
  '/admissions/requirements': typeof AdmissionsRequirementsRoute
  '/contact/enquiry': typeof ContactEnquiryRoute
  '/contact/find-us': typeof ContactFindUsRoute
  '/learning/assessment': typeof LearningAssessmentRoute
  '/learning/culture-values': typeof LearningCultureValuesRoute
  '/learning/curriculum': typeof LearningCurriculumRoute
  '/learning/digital-learning': typeof LearningDigitalLearningRoute
  '/learning/early-years': typeof LearningEarlyYearsRoute
  '/learning/enrichment': typeof LearningEnrichmentRoute
  '/learning/primary': typeof LearningPrimaryRoute
  '/learning/subjects': typeof LearningSubjectsRoute
  '/our-school/about': typeof OurSchoolAboutRoute
  '/our-school/facilities': typeof OurSchoolFacilitiesRoute
  '/our-school/policies': typeof OurSchoolPoliciesRoute
  '/our-school/safeguarding': typeof OurSchoolSafeguardingRoute
  '/our-school/staff': typeof OurSchoolStaffRoute
  '/our-school/vision-values': typeof OurSchoolVisionValuesRoute
  '/our-school/welcome': typeof OurSchoolWelcomeRoute
  '/parents/attendance': typeof ParentsAttendanceRoute
  '/parents/health-wellbeing': typeof ParentsHealthWellbeingRoute
  '/parents/homework-reading': typeof ParentsHomeworkReadingRoute
  '/parents/meals': typeof ParentsMealsRoute
  '/parents/school-day': typeof ParentsSchoolDayRoute
  '/parents/term-dates': typeof ParentsTermDatesRoute
  '/parents/uniform': typeof ParentsUniformRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/our-school/': typeof OurSchoolIndexRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/book-a-visit': typeof BookAVisitRoute
  '/calendar': typeof CalendarRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-portal': typeof ParentPortalRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/admissions/entry-guide': typeof AdmissionsEntryGuideRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/fees': typeof AdmissionsFeesRoute
  '/admissions/how-to-apply': typeof AdmissionsHowToApplyRoute
  '/admissions/requirements': typeof AdmissionsRequirementsRoute
  '/contact/enquiry': typeof ContactEnquiryRoute
  '/contact/find-us': typeof ContactFindUsRoute
  '/learning/assessment': typeof LearningAssessmentRoute
  '/learning/culture-values': typeof LearningCultureValuesRoute
  '/learning/curriculum': typeof LearningCurriculumRoute
  '/learning/digital-learning': typeof LearningDigitalLearningRoute
  '/learning/early-years': typeof LearningEarlyYearsRoute
  '/learning/enrichment': typeof LearningEnrichmentRoute
  '/learning/primary': typeof LearningPrimaryRoute
  '/learning/subjects': typeof LearningSubjectsRoute
  '/our-school/about': typeof OurSchoolAboutRoute
  '/our-school/facilities': typeof OurSchoolFacilitiesRoute
  '/our-school/policies': typeof OurSchoolPoliciesRoute
  '/our-school/safeguarding': typeof OurSchoolSafeguardingRoute
  '/our-school/staff': typeof OurSchoolStaffRoute
  '/our-school/vision-values': typeof OurSchoolVisionValuesRoute
  '/our-school/welcome': typeof OurSchoolWelcomeRoute
  '/parents/attendance': typeof ParentsAttendanceRoute
  '/parents/health-wellbeing': typeof ParentsHealthWellbeingRoute
  '/parents/homework-reading': typeof ParentsHomeworkReadingRoute
  '/parents/meals': typeof ParentsMealsRoute
  '/parents/school-day': typeof ParentsSchoolDayRoute
  '/parents/term-dates': typeof ParentsTermDatesRoute
  '/parents/uniform': typeof ParentsUniformRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/learning': typeof LearningIndexRoute
  '/our-school': typeof OurSchoolIndexRoute
  '/parents': typeof ParentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/book-a-visit': typeof BookAVisitRoute
  '/calendar': typeof CalendarRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-portal': typeof ParentPortalRoute
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/admissions/entry-guide': typeof AdmissionsEntryGuideRoute
  '/admissions/faqs': typeof AdmissionsFaqsRoute
  '/admissions/fees': typeof AdmissionsFeesRoute
  '/admissions/how-to-apply': typeof AdmissionsHowToApplyRoute
  '/admissions/requirements': typeof AdmissionsRequirementsRoute
  '/contact/enquiry': typeof ContactEnquiryRoute
  '/contact/find-us': typeof ContactFindUsRoute
  '/learning/assessment': typeof LearningAssessmentRoute
  '/learning/culture-values': typeof LearningCultureValuesRoute
  '/learning/curriculum': typeof LearningCurriculumRoute
  '/learning/digital-learning': typeof LearningDigitalLearningRoute
  '/learning/early-years': typeof LearningEarlyYearsRoute
  '/learning/enrichment': typeof LearningEnrichmentRoute
  '/learning/primary': typeof LearningPrimaryRoute
  '/learning/subjects': typeof LearningSubjectsRoute
  '/our-school/about': typeof OurSchoolAboutRoute
  '/our-school/facilities': typeof OurSchoolFacilitiesRoute
  '/our-school/policies': typeof OurSchoolPoliciesRoute
  '/our-school/safeguarding': typeof OurSchoolSafeguardingRoute
  '/our-school/staff': typeof OurSchoolStaffRoute
  '/our-school/vision-values': typeof OurSchoolVisionValuesRoute
  '/our-school/welcome': typeof OurSchoolWelcomeRoute
  '/parents/attendance': typeof ParentsAttendanceRoute
  '/parents/health-wellbeing': typeof ParentsHealthWellbeingRoute
  '/parents/homework-reading': typeof ParentsHomeworkReadingRoute
  '/parents/meals': typeof ParentsMealsRoute
  '/parents/school-day': typeof ParentsSchoolDayRoute
  '/parents/term-dates': typeof ParentsTermDatesRoute
  '/parents/uniform': typeof ParentsUniformRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/our-school/': typeof OurSchoolIndexRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/book-a-visit'
    | '/calendar'
    | '/cookie-policy'
    | '/gallery'
    | '/news'
    | '/parent-portal'
    | '/policies'
    | '/privacy-policy'
    | '/search'
    | '/sitemap'
    | '/admissions/entry-guide'
    | '/admissions/faqs'
    | '/admissions/fees'
    | '/admissions/how-to-apply'
    | '/admissions/requirements'
    | '/contact/enquiry'
    | '/contact/find-us'
    | '/learning/assessment'
    | '/learning/culture-values'
    | '/learning/curriculum'
    | '/learning/digital-learning'
    | '/learning/early-years'
    | '/learning/enrichment'
    | '/learning/primary'
    | '/learning/subjects'
    | '/our-school/about'
    | '/our-school/facilities'
    | '/our-school/policies'
    | '/our-school/safeguarding'
    | '/our-school/staff'
    | '/our-school/vision-values'
    | '/our-school/welcome'
    | '/parents/attendance'
    | '/parents/health-wellbeing'
    | '/parents/homework-reading'
    | '/parents/meals'
    | '/parents/school-day'
    | '/parents/term-dates'
    | '/parents/uniform'
    | '/admissions/'
    | '/contact/'
    | '/learning/'
    | '/our-school/'
    | '/parents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/book-a-visit'
    | '/calendar'
    | '/cookie-policy'
    | '/gallery'
    | '/news'
    | '/parent-portal'
    | '/policies'
    | '/privacy-policy'
    | '/search'
    | '/sitemap'
    | '/admissions/entry-guide'
    | '/admissions/faqs'
    | '/admissions/fees'
    | '/admissions/how-to-apply'
    | '/admissions/requirements'
    | '/contact/enquiry'
    | '/contact/find-us'
    | '/learning/assessment'
    | '/learning/culture-values'
    | '/learning/curriculum'
    | '/learning/digital-learning'
    | '/learning/early-years'
    | '/learning/enrichment'
    | '/learning/primary'
    | '/learning/subjects'
    | '/our-school/about'
    | '/our-school/facilities'
    | '/our-school/policies'
    | '/our-school/safeguarding'
    | '/our-school/staff'
    | '/our-school/vision-values'
    | '/our-school/welcome'
    | '/parents/attendance'
    | '/parents/health-wellbeing'
    | '/parents/homework-reading'
    | '/parents/meals'
    | '/parents/school-day'
    | '/parents/term-dates'
    | '/parents/uniform'
    | '/admissions'
    | '/contact'
    | '/learning'
    | '/our-school'
    | '/parents'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/book-a-visit'
    | '/calendar'
    | '/cookie-policy'
    | '/gallery'
    | '/news'
    | '/parent-portal'
    | '/policies'
    | '/privacy-policy'
    | '/search'
    | '/sitemap'
    | '/admissions/entry-guide'
    | '/admissions/faqs'
    | '/admissions/fees'
    | '/admissions/how-to-apply'
    | '/admissions/requirements'
    | '/contact/enquiry'
    | '/contact/find-us'
    | '/learning/assessment'
    | '/learning/culture-values'
    | '/learning/curriculum'
    | '/learning/digital-learning'
    | '/learning/early-years'
    | '/learning/enrichment'
    | '/learning/primary'
    | '/learning/subjects'
    | '/our-school/about'
    | '/our-school/facilities'
    | '/our-school/policies'
    | '/our-school/safeguarding'
    | '/our-school/staff'
    | '/our-school/vision-values'
    | '/our-school/welcome'
    | '/parents/attendance'
    | '/parents/health-wellbeing'
    | '/parents/homework-reading'
    | '/parents/meals'
    | '/parents/school-day'
    | '/parents/term-dates'
    | '/parents/uniform'
    | '/admissions/'
    | '/contact/'
    | '/learning/'
    | '/our-school/'
    | '/parents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BookAVisitRoute: typeof BookAVisitRoute
  CalendarRoute: typeof CalendarRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ParentPortalRoute: typeof ParentPortalRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  ContactEnquiryRoute: typeof ContactEnquiryRoute
  ContactFindUsRoute: typeof ContactFindUsRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  OurSchoolIndexRoute: typeof OurSchoolIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-visit': {
      id: '/book-a-visit'
      path: '/book-a-visit'
      fullPath: '/book-a-visit'
      preLoaderRoute: typeof BookAVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-portal': {
      id: '/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof ParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/entry-guide': {
      id: '/admissions/entry-guide'
      path: '/entry-guide'
      fullPath: '/admissions/entry-guide'
      preLoaderRoute: typeof AdmissionsEntryGuideRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/admissions/faqs': {
      id: '/admissions/faqs'
      path: '/faqs'
      fullPath: '/admissions/faqs'
      preLoaderRoute: typeof AdmissionsFaqsRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/admissions/fees': {
      id: '/admissions/fees'
      path: '/fees'
      fullPath: '/admissions/fees'
      preLoaderRoute: typeof AdmissionsFeesRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/admissions/how-to-apply': {
      id: '/admissions/how-to-apply'
      path: '/how-to-apply'
      fullPath: '/admissions/how-to-apply'
      preLoaderRoute: typeof AdmissionsHowToApplyRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/admissions/requirements': {
      id: '/admissions/requirements'
      path: '/requirements'
      fullPath: '/admissions/requirements'
      preLoaderRoute: typeof AdmissionsRequirementsRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/enquiry': {
      id: '/contact/enquiry'
      path: '/contact/enquiry'
      fullPath: '/contact/enquiry'
      preLoaderRoute: typeof ContactEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/find-us': {
      id: '/contact/find-us'
      path: '/contact/find-us'
      fullPath: '/contact/find-us'
      preLoaderRoute: typeof ContactFindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/assessment': {
      id: '/learning/assessment'
      path: '/assessment'
      fullPath: '/learning/assessment'
      preLoaderRoute: typeof LearningAssessmentRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/culture-values': {
      id: '/learning/culture-values'
      path: '/culture-values'
      fullPath: '/learning/culture-values'
      preLoaderRoute: typeof LearningCultureValuesRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/curriculum': {
      id: '/learning/curriculum'
      path: '/curriculum'
      fullPath: '/learning/curriculum'
      preLoaderRoute: typeof LearningCurriculumRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/digital-learning': {
      id: '/learning/digital-learning'
      path: '/digital-learning'
      fullPath: '/learning/digital-learning'
      preLoaderRoute: typeof LearningDigitalLearningRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/early-years': {
      id: '/learning/early-years'
      path: '/early-years'
      fullPath: '/learning/early-years'
      preLoaderRoute: typeof LearningEarlyYearsRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/enrichment': {
      id: '/learning/enrichment'
      path: '/enrichment'
      fullPath: '/learning/enrichment'
      preLoaderRoute: typeof LearningEnrichmentRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/primary': {
      id: '/learning/primary'
      path: '/primary'
      fullPath: '/learning/primary'
      preLoaderRoute: typeof LearningPrimaryRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/subjects': {
      id: '/learning/subjects'
      path: '/subjects'
      fullPath: '/learning/subjects'
      preLoaderRoute: typeof LearningSubjectsRouteImport
      parentRoute: typeof LearningRoute
    }
    '/our-school/': {
      id: '/our-school/'
      path: '/our-school'
      fullPath: '/our-school/'
      preLoaderRoute: typeof OurSchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-school/about': {
      id: '/our-school/about'
      path: '/about'
      fullPath: '/our-school/about'
      preLoaderRoute: typeof OurSchoolAboutRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/our-school/facilities': {
      id: '/our-school/facilities'
      path: '/facilities'
      fullPath: '/our-school/facilities'
      preLoaderRoute: typeof OurSchoolFacilitiesRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/our-school/policies': {
      id: '/our-school/policies'
      path: '/policies'
      fullPath: '/our-school/policies'
      preLoaderRoute: typeof OurSchoolPoliciesRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/our-school/safeguarding': {
      id: '/our-school/safeguarding'
      path: '/safeguarding'
      fullPath: '/our-school/safeguarding'
      preLoaderRoute: typeof OurSchoolSafeguardingRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/our-school/staff': {
      id: '/our-school/staff'
      path: '/staff'
      fullPath: '/our-school/staff'
      preLoaderRoute: typeof OurSchoolStaffRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/our-school/vision-values': {
      id: '/our-school/vision-values'
      path: '/vision-values'
      fullPath: '/our-school/vision-values'
      preLoaderRoute: typeof OurSchoolVisionValuesRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/our-school/welcome': {
      id: '/our-school/welcome'
      path: '/welcome'
      fullPath: '/our-school/welcome'
      preLoaderRoute: typeof OurSchoolWelcomeRouteImport
      parentRoute: typeof OurSchoolRoute
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/attendance': {
      id: '/parents/attendance'
      path: '/attendance'
      fullPath: '/parents/attendance'
      preLoaderRoute: typeof ParentsAttendanceRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/health-wellbeing': {
      id: '/parents/health-wellbeing'
      path: '/health-wellbeing'
      fullPath: '/parents/health-wellbeing'
      preLoaderRoute: typeof ParentsHealthWellbeingRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/homework-reading': {
      id: '/parents/homework-reading'
      path: '/homework-reading'
      fullPath: '/parents/homework-reading'
      preLoaderRoute: typeof ParentsHomeworkReadingRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/meals': {
      id: '/parents/meals'
      path: '/meals'
      fullPath: '/parents/meals'
      preLoaderRoute: typeof ParentsMealsRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/school-day': {
      id: '/parents/school-day'
      path: '/school-day'
      fullPath: '/parents/school-day'
      preLoaderRoute: typeof ParentsSchoolDayRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/term-dates': {
      id: '/parents/term-dates'
      path: '/term-dates'
      fullPath: '/parents/term-dates'
      preLoaderRoute: typeof ParentsTermDatesRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/uniform': {
      id: '/parents/uniform'
      path: '/uniform'
      fullPath: '/parents/uniform'
      preLoaderRoute: typeof ParentsUniformRouteImport
      parentRoute: typeof ParentsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  BookAVisitRoute: BookAVisitRoute,
  CalendarRoute: CalendarRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ParentPortalRoute: ParentPortalRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  ContactEnquiryRoute: ContactEnquiryRoute,
  ContactFindUsRoute: ContactFindUsRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  OurSchoolIndexRoute: OurSchoolIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
